version: "3"

services:
  ci-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: ci-build
      args:
        GCC_VER: ${GCC_VER}
        CONAN_VER: ${CONAN_VER}
    container_name: cpp-build

  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
      args:
        GCC_VER: ${GCC_VER}
        CONAN_VER: ${CONAN_VER}
        DOCKER_USER: ${DOCKER_USER}
        DOCKER_UID: ${DOCKER_UID}
        DOCKER_GID: ${DOCKER_GID}
    container_name: ${CONTAINER_NAME}
    user: ${DOCKER_UID}:${DOCKER_GID}
    working_dir: ${HOME}/src
    stdin_open: true
    tty: true
    entrypoint: /bin/bash

    environment:
      HOST_HOSTNAME: ${HOSTNAME}
      CONTAINER_NAME: ${CONTAINER_NAME}
      DOCKER_UID: ${DOCKER_UID}
      DOCKER_GID: ${DOCKER_GID}

    volumes:
      - .:${HOME}/src
      - ${HOME}/.ssh:${HOME}/.ssh
